spring:
  config:
    activate:
      on-profile: key
  cloud:
    aws:
      credentials:
        access-key: AKIAXSSTZSMIL6XBC26R
        secret-key: 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
      region:
        static: ap-northeast-2
      s3:
        bucket: dev-impacus-s3

key:
  aes:
    secret-key: 36114567890121556789012326673001
  jwt:
    secret-key: 6B64DCA4E72F58EDIKU9AAB215FE76B64DCA4E72F58EDIKU9AAB215FE7
    accesstoken-validity-in-min: 60
    refreshtoken-validity-in-min: 20160
  bizgo:
    id: impa_om_06y1yv55
    pw: 23670UA10010XGPG71X9
    sender-key: d7c8eea8276eb40356773dc11913c3f3ef8c6ebe
    from-phone: '01071644471'
  payment:
    store-id: store-07021ad4-a603-481e-bec8-48c4419ab304
    smartro:
      channel-key: channel-key-da3b5408-17a4-4f20-8276-77342088e399
      key: 0/4GFsSd7ERVRGX9WHOzJ96GyeMTwvIaKSWUCKmN3fDklNRGw3CualCFoMPZaS99YiFGOuwtzTkrLo4bR4V+Ow==
      cancel-password: 123456
      api-key: +qUx0p3BjGChF4quZogCOJhmFU27RV+EaFJfnnMylY3poGLBm7kgM6YKTDEUL429VF8Fbt9EANbgHOjN/Xu/bA==
    kakao-pay:
      channel-key: channel-key-6a6fabe7-a282-43ad-98e5-816019aa795a
    webhook-key: whsec_xBlV56lIimps/Zt5Z+jLmpYp+DLgJmk/F4+uyraNR8w=
