spring:
  profiles:
    active: dev
    group:
      local:
        - key
        - mail
      dev:
        - key
        - mail
  servlet:
    multipart:
      max-file-size: 24MB
      max-request-size: 30MB
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

logging:
  level:
    org.apache.http: DEBUG
    httpclient.wire: DEBUG