spring:
  config:
    activate:
      on-profile: key
  security:
    oauth2:
      authorized-redirect-uri: http://localhost:3000/auth/login/result
      client:
        provider:
          apple:
            authorizationUri: https://appleid.apple.com/auth/authorize?response_mode=form_post
            tokenUri: https://appleid.apple.com/auth/token
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
        registration:
          apple:
            clientId: implace.kr
            clientSecret: AuthKey_66Y3WF7DG3.p8
            redirect-uri: "https://back-dev.implace.kr/login/oauth2/code/apple"
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Apple
            scope:
              - email
          kakao:
            client-id: 11feba151c9000140c34efa5b250ab61
            client-secret: moqDsduMLshr4nuHasGPX9P993FwHjsS
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: kakao
            scope:
              - account_email
              - profile_nickname
          naver:
            client-id: X6_FJgezg3PARLPaySoQ
            client-secret: NJN4y3oeUE
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-name: Naver
            scope:
              - name
              - email
          google:
            client-id: 541349566703-2dk63jl717cr4aornkpgcmmi462ut9sk.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - profile
              - email
  cloud:
    aws:
      credentials:
        access-key: AKIAXSSTZSMIL6XBC26R
        secret-key: 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
      region:
        static: ap-northeast-2
      s3:
        bucket: dev-impacus-s3

key:
  aes:
    secret-key: 36114567890121556789012326673001
  jwt:
    secret-key: 6B64DCA4E72F58EDIKU9AAB215FE76B64DCA4E72F58EDIKU9AAB215FE7
    accesstoken-validity-in-min: 60
    refreshtoken-validity-in-min: 20160
apple:
  teamId: CML94Q2G94
  keyId: 66Y3WF7DG3
  keyPath: AuthKey_66Y3WF7DG3.p8